config/routes.rb
Rails.application.routes.draw do

  resources :labels
  resources :tasks
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  namespace :admin do
    resources :users
  end

  root to: 'sessions#new'
end

app/models/user.rb
class User < ApplicationRecord
  before_validation :ensure_has_name
  before_update :update_admin_count
  before_destroy :destroy_admin_count

  validates :name, length: { maximum: 30 }
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true
  before_validation { email.downcase! }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  has_many :tasks, dependent: :destroy

  private

  def ensure_has_name
    self.name = 'NoNameUser' if name.blank?
  end

  def destroy_admin_count
    throw(:abort) if User.where(admin: true).length == 1 && self.admin?
  end

  def update_admin_count
    throw(:abort) if User.where(admin: true).length == 1
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_user
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all.order("created_at ASC")
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_user_path(@user.id), notice: '登録しました'
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id), notice: '更新しました'
    else
      redirect_to edit_admin_user_path(@user.id), notice: '更新できません'
    end
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_url, notice: '削除しました'
    else
      redirect_to admin_users_url, notice: '削除できません'
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:index, :edit, :update, :destroy]
  before_action :ensure_correct_user, only: [:show, :edit, :update, :destroy]
  before_action :logout_recommend, only: [:new]

  def index
    @users = User.all.order("created_at ASC")
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to user_path(@user.id), notice: '登録完了！ログインしました！'
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: '更新しました'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: '削除しました'
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def admin_user
    redirect_to users_path, notice: '管理者権限がありません' unless current_user.admin?
  end

  def admin_user_new_or_edit
    if action_name == 'new' || action_name == 'create'
      admin_users_path
    elsif action_name == 'edit'
      admin_user_path
    end
  end

end

app/views/users/_form.html.erb
<% if user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(user.errors.count, "") %> 件のエラーがあります</h2>
    <ul>
    <% user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <br>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <br>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <br>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <br>
    <%= form.password_field :password_confirmation %>
  </div>
<br>
  <div class="actions">
    <%= form.submit :class =>"btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>ユーザー情報編集</h1>

<%= render 'form', user: @user %>
<br>
<%= link_to '詳細', @user, :class =>"btn btn-info" %> |
<%= link_to '一覧', users_path, :class =>"btn btn-info" %>

app/views/users/index.html.erb
<h1>ユーザ一覧</h1>
<div class="panel panel-default container show-table">
  <table class="table">
    <thead>
      <tr>
        <th>名前</th>
        <th>アドレス</th>
        <th>所持タスク数</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.tasks.length %></td>
          <td class="btn-td"><%= link_to '', user, :class =>"glyphicon glyphicon-folder-open btn btn-success" %></td>
          <td class="btn-td"><%= link_to '', edit_user_path(user), :class =>"glyphicon glyphicon-pencil btn btn-warning" %></td>
          <td class="btn-td"><%= link_to '', user, method: :delete, :class =>"glyphicon glyphicon-trash btn btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<h1>ユーザ登録</h1>
<%= render 'form', user: @user %>
<br>
<%= link_to '一覧', users_path, :class =>"btn btn-info" %>

app/views/users/show.html.erb
<h1>ユーザ詳細</h1>
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to '編集', edit_user_path(@user), :class =>"btn btn-info" %> |
<%= link_to '一覧', users_path, :class =>"btn btn-info" %>

<h3>所持タスク一覧</h3>

<div class="panel panel-default container show-table">
  <table class="table">
    <thead>
      <tr>
        <th>タスク名</th>
        <th>タスク内容</th>
        <th>終了期限</th>
        <th>状態</th>
        <th>優先順位</th>
        <th>詳細</th>
        <th>編集</th>
        <th>削除</th>
      </tr>
    </thead>

    <tbody>
      <% @user.tasks.each do |task| %>
          <tr>
            <td><%= task.title %></td>
            <td><%= task.content %></td>
            <td><%= task.deadline.strftime(("%Y年%m月%d日 %H時%M分")) %></td>
            <td><%= task.status %></td>
            <td><%= task.priority %></td>
            <td class="btn-td"><%= link_to '', task, :class =>"glyphicon glyphicon-folder-open btn btn-success" %></td>
            <td class="btn-td"><%= link_to '', edit_task_path(task), :class =>"glyphicon glyphicon-pencil btn btn-warning" %></td>
            <td class="btn-td"><%= link_to '', task, method: :delete, :class =>"glyphicon glyphicon-trash btn btn-danger" %></td>
          </tr>
      <% end %>
    </tbody>
  </table>