config/routes.rb
Rails.application.routes.draw do

  resources :labels
  resources :tasks
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  namespace :admin do
    resources :users
  end

  root to: 'sessions#new'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manyou</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <div class="navbar-brand">Reminder</div>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <% if logged_in?%>
              <li><%= link_to 'Users', users_path %></li>
              <li><%= link_to 'Tasks', tasks_path %></li>
              <li><%= link_to 'NewTask', new_task_path %></li>
              <li><%= link_to "Labels", labels_path %></li>
              <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
              <li><%= link_to "LoginNow：#{current_user.name}", user_path(current_user.id) %></li>
              <li><%= link_to 'AdminPage', admin_users_path %></li>
            <% else %>
              <li><%= link_to 'SignUp', new_user_path %></li>
              <li><%= link_to 'Login', new_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key} notice alert alert-success container") %>
    <% end %>

    <%= yield %>

  </body>
</html>